name: sandgox
on:
  push:
    branches: ["sandbox"]

jobs:
  set-output:
    runs-on: ubuntu-latest
    outputs:
      a: ${{ steps.a.outputs.text }}
    steps:
      - id: a
        # 環境変数のように改行区切りでK,Vを書き込みたいので、コンパクト出力してJSONのインデントと改行を無くす
        run: |
          {
            echo 'text<<EOF'
            echo '[1,2]' | jq .
            echo EOF
          } >> "$GITHUB_OUTPUT"
  
  print-output:
    runs-on: ubuntu-latest
    needs: set-output
    strategy:
      matrix:
        a: ${{ fromJson(needs.set-output.outputs.a) }}
    steps:
      - run: echo ${{ matrix.a }}
